### PR TITLE
Update version to 0.2.3 and workaround for Nim's moveFile() issues on MacOS

### PR DESCRIPTION
**Pull request by gsbabil**
Nim's os.moveFile() would fail to move files on MacOS Big-Sur 11.2 and
fail with the "operation not permitted" error. There are two underlying
issues:

1. Big-Sur's extended file attributes like the followings that mark
   files downloaded from the internet:

    - com.apple.quarantine
    - com.apple.metadata:kMDItemWhereFroms

    As long as these attributes are there, MacOS 11.2 prevents
    moveFile() to function properly. This is worked around by invoking
    `xattr -d` on the attributes mentioned above.

2. However it seems even after the extended attributes are removed,
   moveFile() still tends to fail. This is worked around by using the
   POSIX compatible "mv" utility.

This patch was tested on two separate machines both running MacOS 11.2
with the Firefox Nightly 87.0a1 and Tridactyl 1.20.4pre5209-34b0fce4,
and everything seems to work on MacOS 11.2 so far.

Hope this helps. Thank you.

### CODE REVIEW

File: src/native_main.nim [hunk 1]
```diff
@@ -73,6 +75,34 @@ proc findUserConfigFile(): Option[string] =
 
     return config_path
 
+proc removeFileAttribute(file, attr: string): int =
```
Comment (bovine3dom) [inline src/native_main.nim:78]: If this is OSX only it should probably be wrapped in a when defined : )

File: src/native_main.nim [hunk 2]
```diff
@@ -73,6 +75,34 @@ proc findUserConfigFile(): Option[string] =
...
+    var xattrErr = 0
+    var xattrCmd = ""
+
+    if DEBUG:
+        xattrCmd = quoteShellCommand(["xattr", "-d", attr, file])
+        write(stderr, ">> xattrCmd == " & $xattrCmd & "\n")
+    else:
+        xattrCmd = quoteShellCommand(["xattr", "-d", attr, file])
```
Comment (bovine3dom) [inline src/native_main.nim:86]: These lines are the same, so no need for a `var`

File: src/native_main.nim [hunk 3]
```diff
@@ -73,6 +75,34 @@ proc findUserConfigFile(): Option[string] =
 
     return config_path
 
+proc removeFileAttribute(file, attr: string): int =
+    var xattrErr = 0
+    var xattrCmd = ""
+
+    if DEBUG:
```
Comment (bovine3dom) [inline src/native_main.nim:82]: I think I'd prefer a `log()` function that contained the if to save us having them everywhere

File: src/native_main.nim [hunk 4]
```diff
@@ -73,6 +75,34 @@ proc findUserConfigFile(): Option[string] =
...
+        xattrCmd = quoteShellCommand(["xattr", "-d", attr, file])
```
Comment (bovine3dom) [inline src/native_main.nim:83]: Does xattr require root permissions?

What happens if you try to remove attributes that don't exist on the file?

File: src/native_main.nim [hunk 5]
```diff
@@ -152,15 +182,48 @@ proc handleMessage(msg: MessageRecv): string =
                 reply.code = some(2)
 
         of "move":
-            let
-                dest = expandTilde(msg.to.get())
-                src  = expandTilde(msg.`from`.get())
-            if fileExists(dest):
+            let src = expandTilde(msg.from.get())
+            let dst = expandTilde(msg.to.get())
```
Comment (bovine3dom) [inline src/native_main.nim:186]: `from` is a reserved word in Nim in some contexts. It doesn't matter here but for consistency I'd prefer the backticks remained.

(The backticks allow you to use reserved names as variable names)

File: src/native_main.nim [hunk 6]
```diff
@@ -152,15 +182,48 @@ proc handleMessage(msg: MessageRecv): string =
...
+                            var mvErr = 0
+                            var mvCmd = ""
+                            if DEBUG:
+                                mvCmd = quoteShellCommand(["mv", "-v", "-f", src, dst])
+                                write(stderr, ">> mvCmd == " & $mvCmd & "\n")
+                            else:
+                                mvCmd = quoteShellCommand(["mv", "-f", src, dst])
+
+                            # moveFile(src, dst)
+                            mvErr = execCmd(mvCmd)
```
Comment (bovine3dom) [inline src/native_main.nim:215]: I'm wondering if we should put the flags back here. If people didn't want the flags presumably they'd disable them at a system level? It seems like it shouldn't be a decision that Tridactyl makes

File: src/native_main.nim [hunk 7]
```diff
@@ -233,6 +296,8 @@ proc handleMessage(msg: MessageRecv): string =
 
     return $ %* reply # $ converts to string, %* converts to JSON
 
+parseCommandLineOptions()
```
Comment (bovine3dom) [inline src/native_main.nim:299]: If commandlineparams doesn't exist on all systems, why are we trying to execute this on all systems? It will spam the Firefox error console with warnings that will never be meaningful since Tridactyl will never launch the messenger with command line parameters

File: src/native_main.nim [hunk 8]
```diff
@@ -73,6 +75,36 @@ proc findUserConfigFile(): Option[string] =
...
+proc removeMacOSFileAttribute(file, attr: string): int =
+    var xattrErr = 0
+    var xattrCmd = ""
+
+    debug_log(">> xattrCmd == " & $xattrCmd & "\n")
+
+    xattrCmd = quoteShellCommand(["xattr", "-d", attr, file])
+
+    xattrErr = execCmd(xattrCmd)
+    return xattrErr
```
Comment (bovine3dom) [inline src/native_main.nim:91]: If we don't need this function, can it be removed? Feel free to leave it in the commit history so we can find it again if we do need it.

```suggestion
```

File: src/native_main.nim [hunk 9]
```diff
@@ -155,15 +187,47 @@ proc handleMessage(msg: MessageRecv): string =
...
+                        debug_log(">> MacOS detected ...\n")
+                        var removeAttrErr = 0
+                        # let attrsToRemove = @[
+                        #     "com.apple.quarantine",
+                        #     "com.apple.metadata:kMDItemWhereFroms"
+                        # ]
+                        # for attr in attrsToRemove:
+                        #     removeAttrErr = removeMacOSFileAttribute(src, attr)
+                        #     if removeAttrErr != 0:
+                        #         break
```
Comment (bovine3dom) [inline src/native_main.nim:207]:
```suggestion
```

File: src/native_main.nim [hunk 10]
```diff
@@ -155,15 +187,47 @@ proc handleMessage(msg: MessageRecv): string =
...
+
+            if fileExists(dst):
                 reply.code = some(1)
             else:
                 try:
-                    moveFile(src, dest)
-                    reply.code = some(0)
+                    when defined(macosx):
+                        debug_log(">> MacOS detected ...\n")
+                        var removeAttrErr = 0
```
Comment (bovine3dom) [inline src/native_main.nim:199]:
```suggestion
```

File: src/native_main.nim [hunk 11]
```diff
@@ -155,15 +187,47 @@ proc handleMessage(msg: MessageRecv): string =
...
+                        #     "com.apple.quarantine",
+                        #     "com.apple.metadata:kMDItemWhereFroms"
+                        # ]
+                        # for attr in attrsToRemove:
+                        #     removeAttrErr = removeMacOSFileAttribute(src, attr)
+                        #     if removeAttrErr != 0:
+                        #         break
+
+                        if removeAttrErr == 0:
+                            var mvErr = 0
```
Comment (bovine3dom) [inline src/native_main.nim:210]:
```suggestion
```

File: src/native_main.nim [hunk 12]
```diff
@@ -155,15 +187,47 @@ proc handleMessage(msg: MessageRecv): string =
...
+                            var mvCmd = ""
+                            if DEBUG:
+                                mvCmd = quoteShellCommand(["mv", "-v", "-f", src, dst])
+                                debug_log(">> mvCmd == " & $mvCmd & "\n")
+                            else:
+                                mvCmd = quoteShellCommand(["mv", "-f", src, dst])
+
+                            # moveFile(src, dst)
+                            mvErr = execCmd(mvCmd)
```
Comment (bovine3dom) [inline src/native_main.nim:219]:
```suggestion
                            let mvErr = execCmd(mvCmd)
```

File: src/native_main.nim [hunk 13]
```diff
@@ -155,15 +187,47 @@ proc handleMessage(msg: MessageRecv): string =
...
+                            if DEBUG:
+                                debug_log(">> mvErr == " & $mvErr & "\n")
+
+                            if mvErr == 0:
+                                reply.code = some(0)
+                            else:
+                                raise newException(OSError, "\"" & mvCmd & "\" failed on MacOS ...")
```
Comment (bovine3dom) [inline src/native_main.nim:226]:
```suggestion

                            reply.code = some(mvErr)

```

I think this error handling should probably be in Tridactyl

File: src/native_main.nim [hunk 14]
```diff
@@ -155,15 +187,47 @@ proc handleMessage(msg: MessageRecv): string =
...
+                        #         break
+
+                        if removeAttrErr == 0:
+                            var mvErr = 0
+                            var mvCmd = ""
+                            if DEBUG:
+                                mvCmd = quoteShellCommand(["mv", "-v", "-f", src, dst])
+                                debug_log(">> mvCmd == " & $mvCmd & "\n")
+                            else:
+                                mvCmd = quoteShellCommand(["mv", "-f", src, dst])
```
Comment (bovine3dom) [inline src/native_main.nim:216]:
```suggestion
                            let mvCmd = quoteShellCommand([
                                "mv", "-v",
                                (if DEBUG: "-f" else: ""),
                                src, dst
                            ])
                            debug_log(">> mvCmd == " & $mvCmd & "\n")
```

This should work. Untested

**Comment by gsbabil** [comment]
@bovine3dom 

I've added most of the suggestions above in https://github.com/gsbabil/tridactyl_native_messenger/commit/1462e8cbba987686d44dfcf88634a1a8d59bc178

Regarding https://github.com/tridactyl/native_messenger/pull/26#discussion_r571440319, my remark would be that we already had `OSError` exception handling in line 207 from older code. We have similar `OSError` handling in other places in the existing code too.

So, the new `raise newException(OSError, ...)` on line 202 is not necessarily adding more damage than just jumping to line 207 on any `mv` related error similar to Nim's `moveFile` errors, which requires no immediate changes on the Tridactyl side.

Currently we seem to have the following error-code handling:

- `0`: success
- `1`: file exists
- `2`: move operation failed

`raise newException(OSError, ...)` is just forcing `mv` errors to look like `moveFile` errors and resulting in error-code `2`.

Thank you.

File: src/native_main.nim [hunk 15]
```diff
@@ -152,15 +175,27 @@ proc handleMessage(msg: MessageRecv): string =
...
+            let src = expandTilde(msg.`from`.get())
+            let dst = expandTilde(msg.to.get())
+
+            if fileExists(dst):
                 reply.code = some(1)
             else:
                 try:
-                    moveFile(src, dest)
-                    reply.code = some(0)
+                    when defined(macosx):
```
Comment (bovine3dom) [inline src/native_main.nim:185]:
```suggestion
                    # On OSX, we use POSIX `mv` to bypass restrictions introduced in
                    # Big Sur on moving files downloaded from the internet
                    when defined(macosx):
```

**Comment by bovine3dom** [comment]
@gsbabil I tidied up a few of the commits a little and force-pushed (sorry).

At the time of writing, GitHub CI hasn't run for some reason. I was really hoping it would so I could see if it would build on OSX OK.

I'll check again tomorrow and with luck merge it.

Thanks for working on this : )

**Comment by gsbabil** [comment]
@bovine3dom 

- 55870f266210ef581ec9152dcad4e9f9db777624 gives me the same `saveas` error as with Nim's `moveFile()`, 0818beba3ed9cb962a547f02fb203b7137d9f436 does not.

- I'm also seeing the following new error with Tridactyl `1.20.4pre5214-5724dd96` build.

    ```
    # controller in excmd: Error: Promised response from onMessage listener went out of scope
    ```

Thanks.

**Comment by bovine3dom** [comment]
You're probably seeing https://github.com/tridactyl/native_messenger/commit/3876bcd67fe0f82863d3e9d9ab20ed907dd1ea7e

When are you seeing that error?

**Comment by gsbabil** [comment]
@bovine3dom 

I just freshly checkout https://github.com/tridactyl/native_messenger/commit/55870f266210ef581ec9152dcad4e9f9db777624 again, and confirm that the following snippet is correct in there:

```
                    # On OSX, we use POSIX `mv` to bypass restrictions introduced in
                    # Big Sur on moving files downloaded from the internet
                    when defined(macosx):
                        let mvCmd = quoteShellCommand([
                                "mv", "-f",
                                (if DEBUG: "-v" else: ""),
                                src, dst
                            ])
```
> When are you seeing that error?

When doing things like `saveas ~/Documents`.

Essentially, I'm getting the same old error message that I used to get with `moveFile()` saying `Make sure it doesn't already exist and that all directories of the path exist`. This does not happen if I use 0818beba3ed9cb962a547f02fb203b7137d9f436. Thanks.

**Comment by bovine3dom** [comment]
Could you do a git bisect for me? Is it definitely 55870f2 that introduced it?

**Comment by gsbabil** [comment]
@bovine3dom 

I can't seem to compile any other commits between  55870f2 (`saveas` fails here) and 0818beb (`saveas` works here). I get the following compilation error with the intermediate commits:

```
Error: type mismatch: got <Option[system.int], int literal(0)>
but expected one of:
proc `==`(a, b: Option): bool
  first type mismatch at position: 2
  required type for b: Option
  but expression '0' is of type: int literal(0)
proc `==`[T: tuple | object](x, y: T): bool
  first type mismatch at position: 2
  required type for y: T: tuple or object
  but expression '0' is of type: int literal(0)
31 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: reply.code == 0
       Tip: 5 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: tridactyl_native
        ... Execution failed with exit code 256
```

**Comment by bovine3dom** [comment]
Thanks, I'll try to wrap my head around this later today

**Comment by bovine3dom** [comment]
```
[I] ~/p/tri_native_nim ((0818beba…)|✚1…) $ ./gen_native_message.py cmd..move from..~/foo3 to..~/foo2 | ./native_main
>> MacOS detected ...
>> mvCmd == mv -v -f /home/olie/foo3 /home/olie/foo2
renamed '/home/olie/foo3' -> '/home/olie/foo2'
>> mvErr == 0
v{"cmd":"move","version":null,"content":null,"error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":0}⏎
```

```
[I] ~/p/tri_native_nim (master|✚1…) $ ./gen_native_message.py cmd..move from..~/foo2 to..~/foo3 | ./native_main
>> mvCmd == mv -f -v /home/olie/foo2 /home/olie/foo3
renamed '/home/olie/foo2' -> '/home/olie/foo3'
>> mvStatus == Some(0)
v{"cmd":"move","version":null,"content":null,"error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":0}⏎
```

The only difference I can see is that instead of `mv -v -f` the broken version runs `mv -f -v` (with `debug = true`).

I'm curious - did `0818beb` work for you without `debug = true`? In which case the `-f` flag might not be needed

**Comment by bovine3dom** [comment]
Just in case the order was the problem, 1dd900f swaps it

**Comment by rprimus** [comment]
Tue Feb  9 04:09:50 GMT 2021

For testing, I added a statement to print mvCmd:
```nim
echo "mvCmd: ", mvCmd
```

The last commit produces:

``` sh
: ; ./gen_native_message.py cmd..move from../tmp/zz to../tmp/zz-1  | ./native_main
mvCmd: mv '' -f /tmp/zz /tmp/zz-1
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
v{"cmd":"move","version":null,"content":null,"error":null,"command":null,"sep":null,"files":null,"isDir":null,"code":2}%
```

Note: the first argument to `mv` is the empty string.

To fix this:
```nim
                          let mvCmd = quoteShellCommand([$
                                  "mv",$
                                  (if DEBUG: "-fv" else: "-f"),$
                                  src, dst$
                              ])$
```

**Comment by gsbabil** [comment]
@rprimus @bovine3dom

Thanks for debugging this. I think we should get rid of `-f` altogether and only keep `-v` for `DEBUG`.

Also, I think our handling of `fileExists(...)` check might require further patching. For example, when `:saveas ~/Documents` is performed, it doesn't correctly check if the file-to-be-moved exists in `~/Documents`, and overwrites the file anyway. 

Thank you.

```
                          let mvCmd = quoteShellCommand([
                                  "mv",
                                  (if DEBUG: "-fv" else: "-f"),
                                  src, dst
                              ])
```

**Comment by rprimus** [comment]
Tue Feb  9 07:06:52 GMT 2021

1.  With no `-f`:
```nim
let mvCmd = quoteShellCommand([
        "mv",
        (when defined(DEBUG): "-v"),
        src, dst
    ])
```

2.  How is `DEBUG` set when `native_main` is called from `Tridactyl`?

**Comment by gsbabil** [comment]
@rprimus 

> How is DEBUG set when native_main is called from Tridactyl?

- `DEBUG` is not set from Tridactyl

- We've introduced `--debug/-d` to `native_main` mostly to ease debugging. For example, we can now do `./gen_native_message.py cmd..move from../tmp/xx to../tmp/yy | ./native_main --debug` to get more information useful during debugging.

Thank you.
